spring:
  data:
    redis:
      host: ilovepc.duckdns.org
      password: 'ENC(fweBuucZa1q0tUOBwbIV+1X2rtna2iHZ)'
      port: 26379


jwt:
  secret: 'YVlvdXJWZXJ5TG9uZ0FuZENvbXBsZXhTZWNyZXRLZXlGb3JIUzUxMkFsZ29yaXRobU11c3RCZUF0TGVhc3Q2NEJ5dGVz'
  access-token-validity: 3600000 #3600000 # 1일 (ms)
  refresh-token-validity: 604800000 #604800000 # 7일 (ms)

rdb:
  master:
    jdbcUrl: jdbc:log4jdbc:mysql://ilovepc.duckdns.org:23306
    username: 'ENC(qRj4igOru2fvSCXeo/ncpw==)'
    password: 'ENC(UQNhMbgcTtv2ryTRjTSV2iPjAX2eo6wo)'
mybatis:
  mapper-locations: classpath:mapper/*.xml

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 60s

    instances:
       redis-set:
         base-config: default

apis:
  spcdeEncode: '0CckuwA4JXGq5s8nqHtlutBhsr8wf0xl7yPUS%2B4yybjSb7fYCinkb%2BL6vfqKvlTPaus%2Fc6Lltbvf0Lt8Heo18Q%3D%3D'
  spcdeDecode: 'ENC(EW+tRA5yQP8ubkPzNKyIWzMcWtqviduG8ZIBZPzeVwh/V1IM+Oli9oJ36aFLqSHKfIGAPvjAsNzJ7XoWbCczNifcxfHgmgtbUXonEH7/3yWz/rYYd1kxkTHKZypXUCu3pSKluGYa70A=)'

externalCredencial:
  dhlottery:
    secretId: 'ENC(qllk3UJTQ68fQCEojHcwTkaAggG6cu7C)'
    secretPW: 'ENC(2XuJkrbKkNdBdZCLlSV3YD7e8RZrqgNR)'

server:
  port: 9495